model:
  version: ./models/model_best_v2.h5 # Model version options: upscaler_v1, upscaler_v2 or custom_path to model
  checkpoint: ./models/model_best_v2.ckpt # Only if custom path is below

dataset:
  version: seagull_dataset # Dataset version options: seagull_dataset

learning:
  epoch_amount: 500
  batch_size: 16
  loss: mse # Loss options: mse
  lr: 0.005
  optimizer_type: Adam # Optimizer type options: Adam, SGD
  log_every_n_steps: 5
  # notes: Baseline experiment # Notes for current experiment

server:
  accelerator:
    type: gpu # Accelerator options: gpu, cpu
    devices: 1