model:
  version: upscaler_v1 # done

dataset:
  version: seagull_dataset # done

learning:
  epoch_amount: 200
  batch_size: 16 # done
  loss: mse # done
  lr: 0.005 # done
  scheduler: None
  optimizer_type: Adam # done

server:
  accelerator:
    type: gpu # done
    devices: 1 # done