model:
  version: upscaler_v2

dataset:
  version: seagull_dataset

learning:
  epoch_amount: 200
  batch_size: 16
  loss: mse
  lr: 0.005
  scheduler: None # TODO
  optimizer_type: Adam # [options]: Adam, SGD
  log_every_n_steps: 5

server:
  accelerator:
    type: gpu # [options]: gpu, cpu
    devices: 1 # done